services:
    hello-world:
      image: hello-world
    zbir-brojeva:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - HOST_USER_ID=$HOST_USER_ID
          - HOST_USER_NAME=$HOST_USER_NAME
          - HOST_GROUP_ID=$HOST_GROUP_ID
          - HOST_GROUP_NAME=$HOST_GROUP_NAME
      environment:
        - PORUKA="DOVIDJENJA"
      volumes:
        - ${PWD}:/app/src
        - ./data:/app/data
      tty: true
      stdin_open: true
      image: zbir-brojeva:latest

volumes:
  my_volume1:
  my_volume2: