services:
  hello-world:
    image: hello-world   
  zbir-brojeva:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - HOST_USER_ID=$HOST_USER_ID
        - HOST_USER_NAME=$HOST_USER_NAME
        - HOST_GROUP_ID=$HOST_GROUP_ID
        - HOST_GROUP_NAME=$HOST_GROUP_NAME
    tty: true
    stdin_open: true
    volumes:
      - moj-volume1:/home/outputs
      - ./data:/home/inputs
    environment:
      - UNAME=$UNAME
      - UID=$UID
    image: moj-c-kompajler
    depends_on: 
      - hello-world

volumes:
  moj-volume1: